Summary

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,102 +1,123 @@
-name: "Terraform action"
+name: Sample Action
 on:
   push:
     branches:
       - main
-  pull_request:
-permissions:
-      id-token: write # This is required for aws oidc connection
-      contents: read # This is required for actions/checkout
-      pull-requests: write # This is required for gh bot to comment PR
-env:
-  TF_LOG: INFO
-  AWS_REGION: ${{ secrets.AWS_REGION }}
+    
 jobs:
   deploy:
-    runs-on: ubuntu-latest
+    runs-on:  ubuntu-latest
     defaults:
       run:
         shell: bash
         working-directory: .
-    steps:
-      - name: Git checkout
-        uses: actions/checkout@v3
+      
+      steps:
+        - name: hello world
+          run: console.log("hello world");
 
-      - name: Configure AWS credentials from AWS account
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          role-to-assume: ${{ secrets.AWS_ROLE }}
-          aws-region: ${{ secrets.AWS_REGION }}
-          role-session-name: GitHub-OIDC-TERRAFORM
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: 1.3.7
 
-      - name: Terraform fmt
-        id: fmt
-        run: terraform fmt -check
-        continue-on-error: true
 
-      - name: Terraform Init
-        id: init
-        env:
-          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
-          AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
-        run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}"
+# name: "Terraform action"
+# on:
+#   push:
+#     branches:
+#       - main
+#   pull_request:
+# permissions:
+#       id-token: write # This is required for aws oidc connection
+#       contents: read # This is required for actions/checkout
+#       pull-requests: write # This is required for gh bot to comment PR
+# env:
+#   TF_LOG: INFO
+#   AWS_REGION: ${{ secrets.AWS_REGION }}
+# jobs:
+#   deploy:
+#     runs-on: ubuntu-latest
+#     defaults:
+#       run:
+#         shell: bash
+#         working-directory: .
+#     steps:
+#       - name: Git checkout
+#         uses: actions/checkout@v3
 
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate -no-color
+#       - name: Configure AWS credentials from AWS account
+#         uses: aws-actions/configure-aws-credentials@v1
+#         with:
+#           role-to-assume: ${{ secrets.AWS_ROLE }}
+#           aws-region: ${{ secrets.AWS_REGION }}
+#           role-session-name: GitHub-OIDC-TERRAFORM
 
-      - name: Terraform Plan
-        id: plan
-        run: terraform plan -no-color
-        if: github.event_name == 'pull_request'
-        continue-on-error: true
+#       - name: Setup Terraform
+#         uses: hashicorp/setup-terraform@v2
+#         with:
+#           terraform_version: 1.3.7
 
-      - uses: actions/github-script@v6
-        if: github.event_name == 'pull_request'
-        env:
-          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-            <details><summary>Validation Output</summary>
+#       - name: Terraform fmt
+#         id: fmt
+#         run: terraform fmt -check
+#         continue-on-error: true
 
-            \`\`\`\n
-            ${{ steps.validate.outputs.stdout }}
-            \`\`\`
+#       - name: Terraform Init
+#         id: init
+#         env:
+#           AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
+#           AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
+#         run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}"
 
-            </details>
+#       - name: Terraform Validate
+#         id: validate
+#         run: terraform validate -no-color
 
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+#       - name: Terraform Plan
+#         id: plan
+#         run: terraform plan -no-color
+#         if: github.event_name == 'pull_request'
+#         continue-on-error: true
 
-            <details><summary>Show Plan</summary>
+#       - uses: actions/github-script@v6
+#         if: github.event_name == 'pull_request'
+#         env:
+#           PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+#         with:
+#           github-token: ${{ secrets.GITHUB_TOKEN }}
+#           script: |
+#             const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+#             #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+#             #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+#             <details><summary>Validation Output</summary>
 
-            \`\`\`\n
-            ${process.env.PLAN}
-            \`\`\`
+#             \`\`\`\n
+#             ${{ steps.validate.outputs.stdout }}
+#             \`\`\`
 
-            </details>
+#             </details>
 
-            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+#             #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
 
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
+#             <details><summary>Show Plan</summary>
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+#             \`\`\`\n
+#             ${process.env.PLAN}
+#             \`\`\`
 
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: terraform apply -auto-approve -input=false
+#             </details>
+
+#             *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+
+#             github.rest.issues.createComment({
+#               issue_number: context.issue.number,
+#               owner: context.repo.owner,
+#               repo: context.repo.repo,
+#               body: output
+#             })
+
+#       - name: Terraform Plan Status
+#         if: steps.plan.outcome == 'failure'
+#         run: exit 1
+
+#       - name: Terraform Apply
+#         if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+#         run: terraform apply -auto-approve -input=false
